### ISSUE TITLE
Network choice

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#42] opened 2020-08-21 10:47 UTC
Hi,

How does one chose which network to use for example for artificial labelling since fnet, CARE2D and pix2pix can do it ?
What are the advantages of using one over the other ?

Thank you very much!

**Comment by lucpaul** [comment] 2020-08-24 12:35
Hi, thanks for the question,

what exactly would you like to do with your network and what type of data do you have? 

I would say if you're after artificial labelling, give the fnet notebook a shot, because that is what it was designed for. CARE might be able to do it but it's not necessarily designed to do this, since it's a denoising network. Pix2Pix can do this too, but it uses a different training method which is generative adversarial training, so you can expect the results to look different from fnet which is essentially an autoencoder like Unet (and CARE) without a generator. But from this alone, it's hard to say which one will be better than the other, it can depend on your data. 

More limiting than the networks themselves is probably what data format you have. Our notebook for fnet takes 3D tif stacks as inputs and pix2pix takes 2D .png files as inputs, CARE takes different types depending which CARE notebook you use. That might also be something to consider when picking a network. 
Aside from these data considerations, there are no reasons not to try different networks and see which ones perform the best according to your requirements.

**Comment by lucpaul** [comment] 2020-08-26 16:06
If this answers the question I will close this issue. Feel free to open this again if anything comes up.

**Closed by lucpaul** 2020-08-26 16:06 UTC
