### ISSUE TITLE
Error Transport endpoint is not connected: '/content/gdrive/My Drive/Colab Notebooks/Stardist_v2/Stardist/Models/My_model/config.json'

### ISSUE THREAD

**Issue by mafsousa** [HenriquesLab/ZeroCostDL4Mic#18] opened 2020-05-14 07:56 UTC
**Describe the bug**
After running Stardist model without changing default settings but with new images in the training set, every time I tried to test the model (step 5) that was just created it seems that the connection with google drive doesn't work since is complaining about not finding config.json file.
The way I manage to work around was restarting the session, running the first steps and skipping the training model. 
Then in step 5 unchecked "use current model" and pointed to the folder where the model was. And it worked.

**Screenshots**

```
OSError                                   Traceback (most recent call last)
<ipython-input-13-95cd261c8237> in <module>()
     48   if n_channel > 1:
     49     print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
---> 50   model = StarDist2D(None, name=inference_model_name, basedir=inference_model_path)
     51   #model.optimize_thresholds(X_val, Y_val)
     52 

7 frames
/usr/local/lib/python3.6/dist-packages/stardist/models/model2d.py in __init__(self, config, name, basedir)
    251     def __init__(self, config=Config2D(), name=None, basedir='.'):
    252         """See class docstring."""
--> 253         super().__init__(config, name=name, basedir=basedir)
    254 
    255 

/usr/local/lib/python3.6/dist-packages/stardist/models/base.py in __init__(self, config, name, basedir)
    164 
    165     def __init__(self, config, name=None, basedir='.'):
--> 166         super().__init__(config=config, name=name, basedir=basedir)
    167         threshs = dict(prob=None, nms=None)
    168         if basedir is not None:

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in __init__(self, config, name, basedir)
     90             # config was provided -> update before it is saved to disk
     91             self._update_and_check_config()
---> 92         self._set_logdir()
     93         if config is None:
     94             # config was loaded from disk -> update it after loading

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in wrapper(*args, **kwargs)
     28                 warn is False or warnings.warn("Suppressing call of '%s' (due to basedir=None)." % f.__name__)
     29             else:
---> 30                 return f(*args, **kwargs)
     31         return wrapper
     32     return _suppress_without_basedir

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in _set_logdir(self)
    122         config_file =  self.logdir / 'config.json'
    123         if self.config is None:
--> 124             if config_file.exists():
    125                 config_dict = load_json(str(config_file))
    126                 self.config = self._config_class(**config_dict)

/usr/lib/python3.6/pathlib.py in exists(self)
   1334         """
   1335         try:
-> 1336             self.stat()
   1337         except OSError as e:
   1338             if e.errno not in (ENOENT, ENOTDIR):

/usr/lib/python3.6/pathlib.py in stat(self)
   1156         os.stat() does.
   1157         """
-> 1158         return self._accessor.stat(self)
   1159 
   1160     def owner(self):

/usr/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389 

OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/My Drive/Colab Notebooks/Stardist_v2/Stardist/Models/My_model/config.json'
```

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser: chrome
 - Version: 81.0.4044.138
 - working with remote desktop (vpn)

**Comment by guijacquemet** [comment] 2020-05-14 16:44
Dear @mafsousa 
Many thanks for reaching out!
I cannot reproduce the issue on my end. It sounds to me that you are correct and it is a connection issue with your Gdrive. Could your internet connection be a little unstable?
Also, I see that you are working through a VPN connection? this could contribute to loss of communications if the connection is not too stable. 
Can you reproduce the issue when connected without a VPN?
Cheers
Guillaume

**Comment by mafsousa** [comment] 2020-05-15 09:32
Hi.

I tried without VPN and the error persists. And now is not working in either way. I already tried restarting all and reconnecting colab session. Changing Use_the_current_trained_model also doesn't solve. Any ideas? Maybe I should try a newer release.
![Clipboard-1](https://user-images.githubusercontent.com/56599153/82035339-4a5c1c00-9697-11ea-99cd-9c540d1ec861.jpg)

```
Single images are now beeing predicted
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-39-17edf7f6955a> in <module>()
     50   if n_channel > 1:
     51     print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
---> 52   model = StarDist2D(None, name=inference_model_name, basedir=inference_model_path)
     53   #model.optimize_thresholds(X_val, Y_val)
     54 

7 frames
/usr/local/lib/python3.6/dist-packages/stardist/models/model2d.py in __init__(self, config, name, basedir)
    251     def __init__(self, config=Config2D(), name=None, basedir='.'):
    252         """See class docstring."""
--> 253         super().__init__(config, name=name, basedir=basedir)
    254 
    255 

/usr/local/lib/python3.6/dist-packages/stardist/models/base.py in __init__(self, config, name, basedir)
    164 
    165     def __init__(self, config, name=None, basedir='.'):
--> 166         super().__init__(config=config, name=name, basedir=basedir)
    167         threshs = dict(prob=None, nms=None)
    168         if basedir is not None:

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in __init__(self, config, name, basedir)
     90             # config was provided -> update before it is saved to disk
     91             self._update_and_check_config()
---> 92         self._set_logdir()
     93         if config is None:
     94             # config was loaded from disk -> update it after loading

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in wrapper(*args, **kwargs)
     28                 warn is False or warnings.warn("Suppressing call of '%s' (due to basedir=None)." % f.__name__)
     29             else:
---> 30                 return f(*args, **kwargs)
     31         return wrapper
     32     return _suppress_without_basedir

/usr/local/lib/python3.6/dist-packages/csbdeep/models/base_model.py in _set_logdir(self)
    122         config_file =  self.logdir / 'config.json'
    123         if self.config is None:
--> 124             if config_file.exists():
    125                 config_dict = load_json(str(config_file))
    126                 self.config = self._config_class(**config_dict)

/usr/lib/python3.6/pathlib.py in exists(self)
   1334         """
   1335         try:
-> 1336             self.stat()
   1337         except OSError as e:
   1338             if e.errno not in (ENOENT, ENOTDIR):

/usr/lib/python3.6/pathlib.py in stat(self)
   1156         os.stat() does.
   1157         """
-> 1158         return self._accessor.stat(self)
   1159 
   1160     def owner(self):

/usr/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389 

OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/My Drive/Colab Notebooks/Stardist_v2/Stardist/Model/Phase_Contrast_Model/config.json'
```

**Comment by guijacquemet** [comment] 2020-05-15 16:14
Hi,
Thanks for trying. 
From your screenshot, it looks like you are running a very old version of the stardist notebook.
Have you tried to test the latest version? Do you have the same issue?
I hope this helps
Cheers
Guillaume

**Comment by mafsousa** [comment] 2020-05-18 18:02
HI, today with the new version I didn't have this problem. 
But I had a new error in step 4, because it didn't recognize the files.
I added +"/*.tif", and it worked.
X = sorted(glob(training_images+"/*.tif"))   
Y = sorted(glob(mask_images+"/*.tif"))  

I have another question. the output folder with the model has only 5 text files. How can I use these files in fiji to apply the model in DeepImageJ or in Stardist/Fiji?

Thank you
Mafalda

**Comment by guijacquemet** [comment] 2020-05-18 18:58
Hi,
Thanks for your message. I now realise that you are using the Stardist notebook which has the option to export the trained model to Fiji? I have now updated it to the last version and the issue with the tif files should be fixed.
To export the model to be used in Fiji, run the "Export the model to be used in Fiji" cell once your training is completed. This will create a .zip file that you can load in the Stardist Fiji plugin. 
 In Fiji, Make sure to choose the right version of tensorflow. You can check at: Edit-- Options-- Tensorflow. Choose the version 1.13.1 (CPU or GPU depending on your system). The version 1.14 should also work.

**Closed** 2020-05-29 16:15 UTC
