### ISSUE TITLE
Fail in installing StarDist_3D_ZeroCostDL4Mic on GoogleColab

### ISSUE THREAD

**Issue by peggyscshu** [HenriquesLab/ZeroCostDL4Mic#299] opened 2023-10-24 06:24 UTC
**Describe the bug**
Fail in installing StarDist_3D_ZeroCostDL4Mic on GoogleColab

**To Reproduce**
1. Save "StarDist_3D_ZeroCostDL4Mic.ipynb" as a copy with my Google account.
2. Click on the button 'Play' of the section "1.1. Install StarDist."
3. Wait for couple minutes.
4. See the following error
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.8/69.8 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.7/450.7 kB 5.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.8/136.8 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 941.9/941.9 kB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.9/191.9 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 10.5 MB/s eta 0:00:00
  Building wheel for reikna (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Building wheel for wget (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.1/187.1 kB 2.9 MB/s eta 0:00:00

**Expected behavior**

**Screenshots**
![image](https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/67047201/6b85605f-f757-4397-b7b1-c63182123775)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version [ 118.0.5993.89]

**Additional context**

**Comment by esgomezm** [comment] 2024-01-11 18:04
Hi @peggyscshu 

We have updated the notebooks recently. Does this error persist? Also, the notebook should still work, are you able to train the model and use StarDist?

I'm closing the issue but if the problem is still there, do not hesitate opening it again. 
Thank you
Esti

**Closed by esgomezm** 2024-01-11 18:04 UTC
Labels: bug
