### ISSUE TITLE
Cellpose section 4.2 FileNotFoundError

### ISSUE THREAD

**Issue by Burt3** [HenriquesLab/ZeroCostDL4Mic#232] opened 2022-12-21 21:26 UTC
Hi there, 

I'm experiencing the same problem as a previous user (mafsousa, Mar 2022; and carolche, Oct 27). I am attempting to train my own cellular segmentation model using the cellpose colab but I keep receiving the error - ‘FileNotFoundError: [Errno 2] No such file or directory: ‘/content/BF/train_folder/models’’, after running the cell in section 4.2. 

I am using PNG image files and PNG mask files which contain 5+ masks, the mask files I generated within the cellpose GUI. I have checked and their are no other 'non-image' files in the training folder nor corrupted files. Additionally, I have mounted the images correctly as they were shown correctly in step 3.1, and subsequent steps (up to step 4.2) were also error-free.

I am unsure why this is occurring, and may others are also experiencing the same issue so any help would be greatly appreciated!! :)

**Comment by guijacquemet** [comment] 2023-01-12 07:57
Hi @Burt3,
Thanks for reaching out!
could you share the dataset you are trying to use? I cannot reproduce your error with my test dataset.
Best wishes
Guillaume

**Comment by Burt3** [comment] 2023-01-12 11:29
Hi @guijacquemet 

I've attached below the dataset I have been trying to use. I have already split the training and quality control datasets into their respective images and masks, both in PNG file formats with the same file name.
Your help would be greatly appreciated!!
Best wishes,
Burt

[Test.zip](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/10401092/Test.zip)

**Comment by guijacquemet** [comment] 2023-01-12 15:54
Hi @Burt3 
To train with your dataset, 
- I removed the "@" from the file name (not sure if that's required)
- I resaved your png images as Tif images using Fiji.

For this, I just dragged and dropped each of your folders to open them as stacks in Fiji. Then I resaved your images using "File - save as --- Image sequence. Tick the option "use slice label as file name" to preserve the original name.

But honestly, I would go back and use your original images. Here you have a brightfield image merged into a Fluo image (into RGB). This is perhaps not ideal, and you may get better results by using the raw data.

I hope this helps

Cheers

Guillaume

**Comment by Burt3** [comment] 2023-01-12 16:32
Hi @guijacquemet 

Were you able to train the dataset after doing the above without encountering the error 'FileNotFoundError: [Errno 2] No such file or directory: ‘/content/BF/train_folder/models’’, after running the cell in section 4.2.? 

Thanks,
Burt

**Comment by guijacquemet** [comment] 2023-01-12 17:12
Yes, the training worked.
The No such file or directory: ‘/content/BF/train_folder/models’’ error indicates that the training crashed in your case
[Training dataset.zip](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/10404133/Training.dataset.zip)

**Comment by Burt3** [comment] 2023-01-12 17:22
@guijacquemet 

Okay I see, is there a reason for crashing and can I prevent it? As every time I try to train the same error occurs?

**Comment by guijacquemet** [comment] 2023-01-12 17:27
Most of the time crashes happen because of an issue with the training dataset.
Just to check, which channel do you use for training? Here you have RGB images, so you cannot choose "Grayscale".

**Comment by Burt3** [comment] 2023-01-13 10:32
Hi @guijacquemet 

I believe that was the issue! I split the brightfield and fluorescence channels in Fiji and saved the brightfield image as a Tiff and the training now works using the grayscale channel!
When evaluating my model in section '5.1. Inspection of the loss function', I am unable to run this section as it states 'Not implemented yet', am I not able to evaluate training and validation loss currently? Do you know when this feature will be availiable? 

Thank you so much for your time and help!

**Comment by guijacquemet** [comment] 2023-01-13 10:39
Hi,

Great that it is now working.

I do not know when this feature will be available as we do not have anyone working on this at the moment due to lack of funding.

But you can see these numbers in the training cell output.

Best wishes

Guillaume


On 13 Jan 2023 12:32, Burt3 ***@***.***> wrote:

Hi @guijacquemet<https://github.com/guijacquemet>

I believe that was the issue! I split the brightfield and fluorescence channels in Fiji and saved the brightfield image as a Tiff and the training now works using the grayscale channel!
When evaluating my model in section '5.1. Inspection of the loss function', I am unable to run this section as it states 'Not implemented yet', am I not able to evaluate training and validation loss currently? Do you know when this feature will be availiable?

Thank you so much for your time and help!

**Closed** 2023-01-21 14:52 UTC
